# Додай ці рядки в celery_worker після volumes:
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media

# І те саме в celery_beat після volumes:
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
